<div class="top_nav">
    <div class="the_header_admin">
        <div class="nav_menu">
            <ul class="nav navbar-nav navbar-right">
                <a class="user-profile dropdown-toggle">
                    <img src="" alt="">
                    admin
                    <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="profile_admin pull-right">
                    <li>Profile</li>
                    <li>Đổi mật khẩu</li>
                    <li><a href="">Đăng xuất</a></li>
                </ul>
            </ul>
        </div>
        <div class="the_notification">
            <div class="max_notification">
                <div class="insert_successfuly">
                    <p><i class="fa fa-check-square-o"></i> Bạn đã thêm thành công. </p>
                </div>
                <div class="update_successfuly">
                    <p><i class="fa fa-edit"></i> Bạn đã cập nhật thành công. </p>
                </div>
                <div class="delete_successfuly">
                    <p><i class="fa fa-trash-o"></i> Bạn đã xóa thành công. </p>
                </div>
            </div>
        </div>
    </div>
</div>