<div class="col-md-3 left_col">
    <div class="profile clearfix">
        <div class="profile_info">
            <span>Welcome</span>
            <h2>admin</h2>
        </div>
    </div>
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section active">
            <h3>General management</h3>
            <ul class="nav side-menu">
                <li><a href="<?=PATH?>/mng_user"><i class="fa fa-edit"></i> User </a></li>
                <li><a href="<?=PATH?>/mng_subject"><i class="fa fa-table"></i> Subject </a></li>
                <li><a href="<?=PATH?>/mng_exam"><i class="fa fa-table"></i> Exam </a></li>
                <li><a href="<?=PATH?>/mng_question"><i class="fa fa-clone "></i>Question</a></li>
            </ul>
        </div>
    </div>
</div>